FROM python:3.10-slim

WORKDIR /app

COPY consumer_requirements.txt .
RUN pip install --no-cache-dir -r consumer_requirements.txt

COPY whatsapp_consumer.py .

EXPOSE 8080

CMD ["python", "whatsapp_consumer.py"]
