apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: client
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: kafka
data:
  server.properties: |-
    process.roles=broker,controller
    node.id=1
    controller.quorum.voters=1@kafka:9093
    listeners=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
    advertised.listeners=PLAINTEXT://kafka.kafka.svc.cluster.local:9092
    listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
    log.dirs=/var/lib/kafka/data
  cluster.id: "fvshNY7bTPqFhWF7HFB2cw"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: apache/kafka:3.7.0
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: cluster.id
        - name: KAFKA_LOG_DIRS
          value: "/var/lib/kafka/data"

        command: ["/bin/bash", "-c"]
        args:
        - |
          set -euo pipefail
          if [ ! -f "${KAFKA_LOG_DIRS}/meta.properties" ]; then
            echo "meta.properties not found, formatting storage with cluster id ${KAFKA_CLUSTER_ID}"
            ${KAFKA_HOME:-/opt/kafka}/bin/kafka-storage.sh format -t "${KAFKA_CLUSTER_ID}" -c /opt/kafka/config/kraft/server.properties
          else
            echo "meta.properties already exists in ${KAFKA_LOG_DIRS}, skipping format"
          fi
          exec ${KAFKA_HOME:-/opt/kafka}/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties

        ports:
        - containerPort: 9092
        - containerPort: 9093
        volumeMounts:
        - name: kafka-config
          mountPath: /opt/kafka/config/kraft/server.properties
          subPath: server.properties
        - name: kafka-data
          mountPath: /var/lib/kafka/data

      volumes:
      - name: kafka-config
        configMap:
          name: kafka-config
      - name: kafka-data
        emptyDir: {}
