apiVersion: v1
kind: ConfigMap
metadata:
  name: whatsapp-consumer-config
  namespace: remedios
data:
  TEXT_TOPIC: "whatsapp-text"
  AUDIO_TOPIC: "whatsapp-audio"
  TEXT_ENDPOINT: "http://remetext.remedios.svc.cluster.local:8000/process"
  AUDIO_ENDPOINT: "http://remeaudio.remedios.svc.cluster.local:8000/process"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-consumer
  namespace: remedios
  labels:
    app: whatsapp-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatsapp-consumer
  template:
    metadata:
      labels:
        app: whatsapp-consumer
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
      - name: whatsapp-consumer
        image: ghcr.io/borisfaj/remedios-consumer:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: remedios-config
        - configMapRef:
            name: whatsapp-consumer-config
        env:
        - name: GROUP_ID
          value: "whatsapp-consumer"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
