FROM onerahmet/ffmpeg:n7.1 AS ffmpeg
FROM nvidia/cuda:12.6.3-cudnn-runtime-ubuntu22.04

ARG APP_SRC=.
ENV PYTHON_VERSION=3.10

ENV POETRY_VENV=/app/remedios/.venv
ENV PIP_NO_BINARY=whispercpp
ENV PIP_PREFER_BINARY=0
ENV PYTHONPATH=/app

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get -qq update \
    && apt-get -qq install --no-install-recommends \
    build-essential \
    cmake \
    git \
    python${PYTHON_VERSION} \
    python${PYTHON_VERSION}-venv \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN ln -s -f /usr/bin/python${PYTHON_VERSION} /usr/bin/python3 && \
    ln -s -f /usr/bin/python${PYTHON_VERSION} /usr/bin/python && \
    ln -s -f /usr/bin/pip3 /usr/bin/pip

RUN python3 -m venv $POETRY_VENV \
    && $POETRY_VENV/bin/pip install -U pip setuptools \
    && $POETRY_VENV/bin/pip install poetry==2.1.1

ENV PATH="${PATH}:${POETRY_VENV}/bin"

WORKDIR /app
COPY --from=ffmpeg /usr/local/bin/ffmpeg /usr/local/bin/ffmpeg

COPY ${APP_SRC}/ /app/remedios

WORKDIR /app

RUN poetry config virtualenvs.in-project true
RUN $POETRY_VENV/bin/pip install -r requirements.txt
RUN $POETRY_VENV/bin/pip install -r requirements_audio.txt
RUN $POETRY_VENV/bin/pip install torch==2.6.0 --index-url https://download.pytorch.org/whl/cu126

# Instalar whispercpp desde el repo (fuente) sin binarios precompilados
RUN PIP_NO_BINARY=:all: $POETRY_VENV/bin/pip install --no-cache-dir --no-binary :all: git+https://github.com/stlukey/whispercpp.git

CMD ["/app/remedios/.venv/bin/python", "-m", "remedios.apis.audio_service"]
