apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: remedios-internal-api
  namespace: remedios
spec:
  podSelector:
    matchLabels:
      app: remedios
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: remedios
      ports:
        - protocol: TCP
          port: 3000
