FROM python:3.10-slim

WORKDIR /app

COPY zordon/core/consumer_requirements.txt .
RUN pip install --no-cache-dir -r consumer_requirements.txt

COPY zordon/core/whatsapp_consumer.py .

EXPOSE 8080

CMD ["python", "whatsapp_consumer.py"]
