FROM python:3.10-slim

WORKDIR /app

COPY core/server_requirements.txt /app/
RUN pip install --no-cache-dir -r server_requirements.txt

COPY core/server.py /app/

EXPOSE 3000

CMD ["python", "/app/server.py"]
