version: "3"
services:
  zookeeper:
    image: blacktop/kafka:${VERSION:-latest}
    container_name: zookeeper
    command: zookeeper-server-start.sh config/zookeeper.properties
    ports:
      - "2181:2181"
    networks:
      - kafka_network

  kafka:
    image: blacktop/kafka:${VERSION:-latest}
    container_name: kafka
    depends_on:
      - zookeeper
    entrypoint: /wait-for-it.sh zookeeper:2181 -s --timeout=5 -- /kafka-entrypoint.sh
    command: kafka-server-start.sh config/server.properties
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://remediosapi.duckdns.org:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_HEAP_OPTS=-Xmx512m -Xms256m
      - KAFKA_CREATE_TOPICS=whatsapp-events:1:1
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - kafka_network
  flask-server:
    build: server/.
    container_name: flask-server
    depends_on:
       - kafka
    environment:
      - KAFKA_BROKER=kafka:9092  # Kafka está en la misma red
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=eu-north-1
    ports:
      - "3000:3000"
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge

